#!/bin/bash

for filename in *.*
do
  if [ -f "$filename" ]
  then
    lupdate -codecfortr utf8 -pro "../HttpLoader.pro" -ts "$filename"
    lupdate-qt4 -codecfortr utf8 -pro "../HttpLoader.pro" -ts "$filename"
  fi
done